In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.read_csv("/Users/mac/Desktop/DATA ANALYSIS/Dataverse Internship/Project_3/SQL FILES/claims_clean.csv")

,claim_id,patient_id,encounter_id,provider_id,provider_name,department,admission_date,discharge_date,claim_submission_date,icd10_primary,...,claim_status,denial_reason,payer_type,claim_processing_days,is_duplicate_claim,paid_error,claim_before_discharge,claim_before_admission,days_to_submit,is_pending
0,CLM03823,PAT0269,ENC03823,P011,Dr. Ibrahim Musa,Emergency,2024-10-29,2024-11-06,2024-11-19,F321,...,Paid,NaN,Insurance,15,0,0,0,0,13,NaN
1,CLM02123,PAT1446,ENC02123,P011,Dr. Ibrahim Musa,Emergency,2024-03-28,2024-04-06,2024-05-01,J18,...,Paid,NaN,Government,23,0,0,0,0,25,NaN
2,CLM03420,PAT0929,ENC03420,P003,Dr. Chukwuemeka Eze,Oncology,2024-02-15,2024-02-24,2024-04-01,I10,...,Appealed,Incomplete Documentation,Insurance,5,0,0,0,0,37,NaN
3,CLM00467,PAT0306,ENC00467,P012,Dr. Chioma Obi,Internal Medicine,2024-02-06,2024-02-07,2024-02-17,M545,...,Denied,Duplicate Claim,Insurance,1,1,0,0,0,10,NaN
4,CLM06012,PAT0541,ENC04325,P008,Dr. Seun Afolabi,General Surgery,2024-10-05,2024-10-07,2024-11-10,K921,...,Denied,Duplicate Claim,Insurance,46,1,0,0,0,34,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6145,CLM03773,PAT0930,ENC03773,P003,Dr. Chukwuemeka Eze,Internal Medicine,2024-10-25,2024-10-26,2024-11-08,M545,...,Paid,NaN,Insurance,26,0,0,0,0,13,NaN
6146,CLM05192,PAT1040,ENC05192,P002,Dr. Fatima Bello,Oncology,2024-09-23,2024-09-27,2024-10-08,I10,...,Paid,NaN,Insurance,57,0,0,0,0,11,NaN
6147,CLM05391,PAT0385,ENC05391,P003,Dr. Chukwuemeka Eze,Pediatrics,2024-04-12,2024-04-20,2024-05-21,J441,...,Paid,NaN,Insurance,19,0,0,0,0,31,NaN
6148,CLM00861,PAT0902,ENC00861,P010,Dr. Yetunde Okafor,Pediatrics,2024-01-22,2024-01-31,2024-02-15,I10,...,Denied,Incomplete Documentation,Insurance,23,0,0,0,0,15,NaN
6149,CLM05227,PAT0750,ENC05227,P007,Dr. Emeka Nwosu,General Surgery,2024-11-19,2024-11-25,2024-11-16,I10,...,Denied,Patient Not Eligible,Insurance,47,0,0,1,0,-9,NaN

In [3]:
df=pd.read_csv("/Users/mac/Desktop/DATA ANALYSIS/Dataverse Internship/Project_3/SQL FILES/claims_clean.csv")

INSPECTING THE DATASET

In [5]:
df.head()

,claim_id,patient_id,encounter_id,provider_id,provider_name,department,admission_date,discharge_date,claim_submission_date,icd10_primary,...,claim_status,denial_reason,payer_type,claim_processing_days,is_duplicate_claim,paid_error,claim_before_discharge,claim_before_admission,days_to_submit,is_pending
0,CLM03823,PAT0269,ENC03823,P011,Dr. Ibrahim Musa,Emergency,2024-10-29,2024-11-06,2024-11-19,F321,...,Paid,NaN,Insurance,15,0,0,0,0,13,NaN
1,CLM02123,PAT1446,ENC02123,P011,Dr. Ibrahim Musa,Emergency,2024-03-28,2024-04-06,2024-05-01,J18,...,Paid,NaN,Government,23,0,0,0,0,25,NaN
2,CLM03420,PAT0929,ENC03420,P003,Dr. Chukwuemeka Eze,Oncology,2024-02-15,2024-02-24,2024-04-01,I10,...,Appealed,Incomplete Documentation,Insurance,5,0,0,0,0,37,NaN
3,CLM00467,PAT0306,ENC00467,P012,Dr. Chioma Obi,Internal Medicine,2024-02-06,2024-02-07,2024-02-17,M545,...,Denied,Duplicate Claim,Insurance,1,1,0,0,0,10,NaN
4,CLM06012,PAT0541,ENC04325,P008,Dr. Seun Afolabi,General Surgery,2024-10-05,2024-10-07,2024-11-10,K921,...,Denied,Duplicate Claim,Insurance,46,1,0,0,0,34,NaN

In [6]:
df.tail()

,claim_id,patient_id,encounter_id,provider_id,provider_name,department,admission_date,discharge_date,claim_submission_date,icd10_primary,...,claim_status,denial_reason,payer_type,claim_processing_days,is_duplicate_claim,paid_error,claim_before_discharge,claim_before_admission,days_to_submit,is_pending
6145,CLM03773,PAT0930,ENC03773,P003,Dr. Chukwuemeka Eze,Internal Medicine,2024-10-25,2024-10-26,2024-11-08,M545,...,Paid,NaN,Insurance,26,0,0,0,0,13,NaN
6146,CLM05192,PAT1040,ENC05192,P002,Dr. Fatima Bello,Oncology,2024-09-23,2024-09-27,2024-10-08,I10,...,Paid,NaN,Insurance,57,0,0,0,0,11,NaN
6147,CLM05391,PAT0385,ENC05391,P003,Dr. Chukwuemeka Eze,Pediatrics,2024-04-12,2024-04-20,2024-05-21,J441,...,Paid,NaN,Insurance,19,0,0,0,0,31,NaN
6148,CLM00861,PAT0902,ENC00861,P010,Dr. Yetunde Okafor,Pediatrics,2024-01-22,2024-01-31,2024-02-15,I10,...,Denied,Incomplete Documentation,Insurance,23,0,0,0,0,15,NaN
6149,CLM05227,PAT0750,ENC05227,P007,Dr. Emeka Nwosu,General Surgery,2024-11-19,2024-11-25,2024-11-16,I10,...,Denied,Patient Not Eligible,Insurance,47,0,0,1,0,-9,NaN

In [7]:
df.describe()

,cpt_procedure,billed_amount,allowed_amount,paid_amount,claim_processing_days,is_duplicate_claim,paid_error,claim_before_discharge,claim_before_admission,days_to_submit,is_pending
count,6150.000000,6150.000000,6150.000000,6150.000000,6150.000000,6150.000000,6150.000000,6150.000000,6150.0,6150.000000,553.0
mean,76563.539675,2972.969039,2328.364780,1111.215767,30.377724,0.078049,0.012033,0.019675,0.0,22.679837,1.0
std,24419.345323,1902.058345,1500.711147,1551.918541,17.419002,0.268270,0.109040,0.138891,0.0,13.510256,0.0
min,27447.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.0,-10.000000,1.0
25%,47562.000000,1467.157500,1148.052500,0.000000,15.000000,0.000000,0.000000,0.000000,0.0,11.000000,1.0
50%,81001.000000,2723.525000,2111.125000,0.000000,30.000000,0.000000,0.000000,0.000000,0.0,23.000000,1.0
75%,99214.000000,4210.392500,3272.440000,2027.102500,46.000000,0.000000,0.000000,0.000000,0.0,34.000000,1.0
max,99233.000000,8714.060000,7880.070000,7727.100000,60.000000,1.000000,1.000000,1.000000,0.0,56.000000,1.0

In [8]:
df.describe(include ='object')

,claim_id,patient_id,encounter_id,provider_id,provider_name,department,admission_date,discharge_date,claim_submission_date,icd10_primary,icd10_description,claim_status,denial_reason,payer_type
count,6150,6150,6150,6150,6150,6150,6150,6150,6150,6150,6150,6150,2713,6150
unique,6150,1476,6000,12,12,8,365,374,410,15,15,4,8,4
top,CLM03823,PAT1130,ENC02046,P009,Dr. Kofi Asante,Emergency,2024-10-13,2024-02-05,2024-06-07,E11,Type 2 Diabetes Mellitus,Paid,Duplicate Claim,Insurance
freq,1,15,2,545,545,818,28,29,31,768,768,2884,480,3261

In [9]:
df.shape

(6150, 25)

In [10]:
df.columns

Index(['claim_id', 'patient_id', 'encounter_id', 'provider_id',
       'provider_name', 'department', 'admission_date', 'discharge_date',
       'claim_submission_date', 'icd10_primary', 'icd10_description',
       'cpt_procedure', 'billed_amount', 'allowed_amount', 'paid_amount',
       'claim_status', 'denial_reason', 'payer_type', 'claim_processing_days',
       'is_duplicate_claim', 'paid_error', 'claim_before_discharge',
       'claim_before_admission', 'days_to_submit', 'is_pending'],
      dtype='object')

In [11]:
df.dtypes

claim_id                   object
patient_id                 object
encounter_id               object
provider_id                object
provider_name              object
department                 object
admission_date             object
discharge_date             object
claim_submission_date      object
icd10_primary              object
icd10_description          object
cpt_procedure               int64
billed_amount             float64
allowed_amount            float64
paid_amount               float64
claim_status               object
denial_reason              object
payer_type                 object
claim_processing_days       int64
is_duplicate_claim          int64
paid_error                  int64
claim_before_discharge      int64
claim_before_admission      int64
days_to_submit              int64
is_pending                float64
dtype: object

In [12]:
df.isnull().sum()

claim_id                     0
patient_id                   0
encounter_id                 0
provider_id                  0
provider_name                0
department                   0
admission_date               0
discharge_date               0
claim_submission_date        0
icd10_primary                0
icd10_description            0
cpt_procedure                0
billed_amount                0
allowed_amount               0
paid_amount                  0
claim_status                 0
denial_reason             3437
payer_type                   0
claim_processing_days        0
is_duplicate_claim           0
paid_error                   0
claim_before_discharge       0
claim_before_admission       0
days_to_submit               0
is_pending                5597
dtype: int64

CLEANED RECORD (REMOVING DUPLICATES)

In [14]:


# Turn 'Denied' into 1 and 'Paid' into 0
df['is_denied'] = (df['claim_status'] == 'Denied').astype(int)

In [15]:
df_unique = df[df['is_duplicate_claim'] == 0].copy()


df_unique['is_denied'] = (df_unique['claim_status'] == 'Denied').astype(int)


total_unique_claims = len(df_unique)
total_denied = df_unique['is_denied'].sum()
denial_rate = df_unique['is_denied'].mean()


print(f"Total Unique Claims: {total_unique_claims}")
print(f"Total Unique Denials: {total_denied}")
print(f"Overall Denial Rate: {denial_rate:.2%}")

Total Unique Claims: 5670
Total Unique Denials: 1993
Overall Denial Rate: 35.15%

In [16]:
# Calculate the overall rate first
overall_rate = df['is_denied'].mean()
print(f"Overall Denial Rate: {overall_rate:.2%}")

Overall Denial Rate: 39.58%

DENIAL RATE BY DEPARTMENT

In [18]:
dept_denial_rate = df_unique.groupby('department')['is_denied'].agg(
    total_claims='count',
    total_denied='sum',
    denial_rate='mean'
).sort_values(by='denial_rate', ascending=False)

print(dept_denial_rate)

                   total_claims  total_denied  denial_rate
department
Pediatrics                  709           264     0.372355
Emergency                   749           271     0.361816
General Surgery             680           240     0.352941
Neurology                   743           262     0.352624
Oncology                    711           248     0.348805
Cardiology                  719           250     0.347705
Orthopedics                 682           237     0.347507
Internal Medicine           677           221     0.326440

DENIAL RATE BY PROVIDER

In [20]:
# Grouping to see the stats by category
provider_denial_rate = df_unique.groupby('provider_name')['is_denied'].agg(
    total_claims='count',
    total_denied='sum',
    denial_rate='mean'
).sort_values(by='denial_rate', ascending=False)

print(provider_denial_rate)

                     total_claims  total_denied  denial_rate
provider_name
Dr. Yetunde Okafor            447           169     0.378076
Dr. Kwame Mensah              492           177     0.359756
Dr. Emeka Nwosu               450           161     0.357778
Dr. Aisha Kamara              459           163     0.355120
Dr. Fatima Bello              439           155     0.353075
Dr. Chukwuemeka Eze           500           176     0.352000
Dr. Ngozi Adeyemi             470           165     0.351064
Dr. Chioma Obi                486           170     0.349794
Dr. Ibrahim Musa              447           155     0.346756
Dr. Amara Osei                499           170     0.340681
Dr. Kofi Asante               502           170     0.338645
Dr. Seun Afolabi              479           162     0.338205

DENIAL RATE BY PAYER TYPE

In [22]:
payer_denial_rate = df_unique.groupby('payer_type')['is_denied'].agg(
    total_claims='count',
    total_denied='sum',
    denial_rate='mean'
).sort_values(by='denial_rate', ascending=False)

print(payer_denial_rate)

            total_claims  total_denied  denial_rate
payer_type
Self-Pay             839           309     0.368296
Government          1592           573     0.359925
Insurance           3010          1041     0.345847
Unknown              229            70     0.305677

DENIAL RATE BY ICD10

In [24]:
ICD10_denial_rate = df_unique.groupby('icd10_primary')['is_denied'].agg(
    total_claims='count',
    total_denied='sum',
    denial_rate='mean'
).sort_values(by='denial_rate', ascending=False)

print(ICD10_denial_rate)

               total_claims  total_denied  denial_rate
icd10_primary
J18                     567           214     0.377425
Z3800                   312           117     0.375000
M545                    437           162     0.370709
N390                    591           213     0.360406
A09                     247            89     0.360324
J441                    347           123     0.354467
K921                    235            83     0.353191
F321                    244            85     0.348361
I639                    207            72     0.347826
E11                     705           245     0.347518
B349                    265            91     0.343396
I2510                   469           161     0.343284
C3410                   159            53     0.333333
I10                     661           215     0.325265
S72001A                 224            70     0.312500

REVENUE LEAKAGE: Money hospitals should have earned from patient care, but did not receive because claims were denied, delayed, or rejected....Duplicate denied claims were identified and removed prior to analysis to prevent overestimation of revenue leakage.”

In [26]:
#Filter for claims that are Denied AND NOT duplicates
true_denied_claims = df[(df['claim_status'] == 'Denied') & (df['is_duplicate_claim'] == 0)]

#Calculate the ACCURATE Total Leakage
true_revenue_leakage = true_denied_claims['billed_amount'].sum()

#Calculate the "False" Leakage
false_total_leakage = df[df['claim_status'] == 'Denied']['billed_amount'].sum()
inflation_amount = false_total_leakage - true_revenue_leakage

print(f"True Revenue Leakage: ${true_revenue_leakage:,.2f}")
print(f"Amount Overstated by Duplicates: ${inflation_amount:,.2f}")

True Revenue Leakage: $5,928,086.53
Amount Overstated by Duplicates: $1,288,642.67

In [27]:
Df_unique = df[df['is_duplicate_claim'] == 0].copy()
df_denied = df_unique[df_unique['claim_status'] == 'Denied']

# Group by department and calculate the metrics
leakage_by_department = (
    df_denied.groupby('department')
    .agg(
        total_leakage=('billed_amount', 'sum'),
        total_claims=('billed_amount', 'count')
    )
    .sort_values(by='total_leakage', ascending=False)
    .reset_index()
)

print(leakage_by_department)

          department  total_leakage  total_claims
0          Emergency      854954.14           271
1           Oncology      771688.52           248
2          Neurology      770286.32           262
3         Pediatrics      728225.33           264
4        Orthopedics      718586.80           237
5    General Surgery      706631.08           240
6         Cardiology      706552.73           250
7  Internal Medicine      671161.61           221

LEAKED BY PROVIDER

In [29]:
df_unique = df[df['is_duplicate_claim'] == 0].copy()
df_denied = df_unique[df_unique['claim_status'] == 'Denied']


leakage_by_provider = (
    df_denied.groupby('provider_name')
    .agg(
        total_leakage=('billed_amount', 'sum'),
        total_claims=('billed_amount', 'count')
    )
    .sort_values(by='total_leakage', ascending=False)
    .reset_index()
)
print(leakage_by_provider)

          provider_name  total_leakage  total_claims
0        Dr. Chioma Obi      532719.94           170
1      Dr. Kwame Mensah      526188.90           177
2   Dr. Chukwuemeka Eze      523459.26           176
3      Dr. Aisha Kamara      508547.81           163
4       Dr. Kofi Asante      504585.09           170
5    Dr. Yetunde Okafor      501622.93           169
6        Dr. Amara Osei      500132.98           170
7       Dr. Emeka Nwosu      478332.47           161
8      Dr. Seun Afolabi      471577.10           162
9     Dr. Ngozi Adeyemi      468869.10           165
10     Dr. Ibrahim Musa      461306.31           155
11     Dr. Fatima Bello      450744.64           155

LEAKAGE BY PAYER TYPE

In [31]:
df_denied = df[df['claim_status'] == 'Denied']


leakage_by_payer = (
    df_denied.groupby('payer_type')
    .agg(
        total_leakage=('billed_amount', 'sum'),
        total_claims=('billed_amount', 'count')
    )
    .sort_values(by='total_leakage', ascending=False)
    .reset_index()
)
print(leakage_by_payer)

   payer_type  total_leakage  total_claims
0   Insurance     3827499.22          1268
1  Government     2104881.59           710
2    Self-Pay     1037491.33           367
3     Unknown      246857.06            89

COMPARISON WITH DUPLICATES

CORRELATION ANALYSIS

In [34]:

df['is_denied'] = (df['claim_status'] == 'Denied').astype(int)


print("Correlation Analysis")
corr_table = df[['billed_amount', 'claim_processing_days', 'is_denied']].corr()
display(corr_table)

print("\n")


means_table = df.groupby('is_denied')[['billed_amount', 'claim_processing_days']].mean()
display(means_table)

Correlation Analysis

                       billed_amount  claim_processing_days  is_denied
billed_amount               1.000000               0.004953  -0.003405
claim_processing_days       0.004953               1.000000  -0.008483
is_denied                  -0.003405              -0.008483   1.000000

           billed_amount  claim_processing_days
is_denied
0            2978.210546              30.497309
1            2964.966804              30.195152

DENIAL REASON ANALYSIS

In [36]:
#Calculate leakage and count by reason
leakage_by_reason = (
    df.groupby('denial_reason')
    .agg(
        total_leakage=('billed_amount', 'sum'),
        claim_count=('billed_amount', 'count')
    )
    .sort_values(by='total_leakage', ascending=False)
    .reset_index()
)

#percentage of total leakage column
total_lost = leakage_by_reason['total_leakage'].sum()
leakage_by_reason['%_of_total_leakage'] = (leakage_by_reason['total_leakage'] / total_lost) * 100

# Display the results
display(leakage_by_reason)

              denial_reason  total_leakage  claim_count  %_of_total_leakage
0           Duplicate Claim     1407875.16          480           17.540745
1         Medical Necessity     1172652.42          368           14.610100
2      Patient Not Eligible     1024187.31          346           12.760371
3    Timely Filing Exceeded     1001850.44          333           12.482075
4              Coding Error      997600.14          349           12.429120
5  Incomplete Documentation      984553.22          338           12.266569
6     Missing Authorization      875867.50          316           10.912451
7                   Unknown      561727.06          183            6.998569

CORRELATION ANALYSIS

 Top 5 provider-diagnosis combinations with the highest denial rates.

In [39]:
#Group by both Provider and Diagnosis
#Calculate the mean (Denial Rate) and count (Volume)
cohort_analysis = (
    df.groupby(['provider_name', 'icd10_description'])['is_denied']
    .agg(['mean', 'count'])
    .reset_index()
    )

top_5_cohorts = (
    cohort_analysis[cohort_analysis['count'] >= 5]
    .sort_values(by='mean', ascending=False)
    .head(5)
)

print("--- Top 5 Provider-Diagnosis Denial Cohorts ---")
display(top_5_cohorts)

--- Top 5 Provider-Diagnosis Denial Cohorts ---

          provider_name          icd10_description      mean  count
179  Dr. Yetunde Okafor            Viral Infection  0.705882     17
42       Dr. Chioma Obi   Type 2 Diabetes Mellitus  0.595745     47
159    Dr. Seun Afolabi                     Melena  0.583333     24
91     Dr. Ibrahim Musa        Cerebral Infarction  0.583333     24
98     Dr. Ibrahim Musa  Major Depressive Disorder  0.578947     19

DENIAL RISK FLAG

In [41]:
# Create Risk Factors

# High-risk payer
df['risk_payer'] = df['payer_type'].isin(['Government', 'Insurance', 'Self-Pay']).astype(int)

In [42]:
# Late processing
threshold_days = df['claim_processing_days'].median()

df['risk_processing'] = (df['claim_processing_days'] > threshold_days).astype(int)

In [43]:
# High billed amount
threshold_amount = df['billed_amount'].median()

df['risk_amount'] = (df['billed_amount'] > threshold_amount).astype(int)

In [44]:
# Create Risk Score
df['risk_score'] = (
    df['risk_payer'] +
    df['risk_processing'] +
    df['risk_amount']
)
print(df['risk_score'])

0       2
1       2
2       1
3       2
4       3
       ..
6145    2
6146    3
6147    1
6148    2
6149    2
Name: risk_score, Length: 6150, dtype: int64

In [76]:
import os

output_folder = "outputs"  # you can rename this (e.g., "claims_outputs")

# Create folder if it doesn't exist
os.makedirs(output_folder, exist_ok=True)

In [78]:
df.to_csv(os.path.join(output_folder, "claims_output.csv"), index=False)

pd.DataFrame({'total_unique_claims': [total_unique_claims]}).to_csv(os.path.join(output_folder, "total_unique_claims.csv"), index=False)
pd.DataFrame({'total_denied': [total_denied]}).to_csv(os.path.join(output_folder, "total_denied.csv"), index=False)
pd.DataFrame({'denial_rate': [denial_rate]}).to_csv(os.path.join(output_folder, "denial_rate.csv"), index=False)

pd.DataFrame({'overall_rate': [overall_rate]}).to_csv(os.path.join(output_folder, "overall_rate.csv"), index=False)

# Denial breakdowns
dept_denial_rate.to_csv(os.path.join(output_folder, "dept_denial_rate.csv"), index=False)
provider_denial_rate.to_csv(os.path.join(output_folder, "provider_denial_rate.csv"), index=False)
payer_denial_rate.to_csv(os.path.join(output_folder, "payer_denial_rate.csv"), index=False)
ICD10_denial_rate.to_csv(os.path.join(output_folder, "ICD10_denial_rate.csv"), index=False)

# Revenue leakage
pd.DataFrame({'true_revenue_leakage': [true_revenue_leakage]}).to_csv(os.path.join(output_folder, "true_revenue_leakage.csv"), index=False)
pd.DataFrame({'false_total_leakage': [false_total_leakage]}).to_csv(os.path.join(output_folder, "false_total_leakage.csv"), index=False)
pd.DataFrame({'inflation_amount': [inflation_amount]}).to_csv(os.path.join(output_folder, "inflation_amount.csv"), index=False)

# Leakage breakdown
leakage_by_department.to_csv(os.path.join(output_folder, "leakage_by_department.csv"), index=False)
leakage_by_provider.to_csv(os.path.join(output_folder, "leakage_by_provider.csv"), index=False)
leakage_by_payer.to_csv(os.path.join(output_folder, "leakage_by_payer.csv"), index=False)

# Comparison with duplicates
pd.DataFrame({'false_total_leakage': [false_total_leakage]}).to_csv(os.path.join(output_folder, "raw_leakage.csv"), index=False)
pd.DataFrame({'true_revenue_leakage': [true_revenue_leakage]}).to_csv(os.path.join(output_folder, "true_revenue_leakage.csv"), index=False)

# Correlation
corr_table.to_csv(os.path.join(output_folder, "corr_table.csv"), index=False)
means_table.to_csv(os.path.join(output_folder, "means_table.csv"), index=False)

# Denial reason analysis
leakage_by_reason.to_csv(os.path.join(output_folder, "leakage_by_reason.csv"), index=False)
pd.DataFrame({'total_lost': [total_lost]}).to_csv(os.path.join(output_folder, "total_lost.csv"), index=False)

# Top 5 cohorts
top_5_cohorts.to_csv(os.path.join(output_folder, "top_5_cohorts.csv"), index=False)